version: '3.8'

services:

  db:
    container_name: postgresql-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

    volumes:
      - ./postgre_data/data:/var/lib/postgresql/data

volumes:
  postgres_data: