# Generated by Django 4.0.2 on 2022-04-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_cars', models.IntegerField()),
                ('aggregation_date', models.DateField()),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
